SELECT NAME FROM COUNTRY;
SELECT NAME, SURFACEAREA FROM COUNTRY;
SELECT NAME FROM COUNTRY WHERE CONTINENT = 'EUROPE';
SELECT NAME FROM COUNTRY WHERE POPULATION > 10000000;
SELECT NAME, POPULATION FROM COUNTRY WHERE POPULATION > 10000000 AND CONTINENT = 'EUROPE';
SELECT NAME FROM COUNTRY ORDER BY NAME;
SELECT NAME, CAPITAL, POPULATION FROM COUNTRY WHERE NAME = 'POLAND';
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT CO.NAME, CI.NAME AS CAPITAL 
FROM COUNTRY CO
JOIN CITY CI ON CO.CAPITAL = CI.ID
WHERE CI.POPULATION > 500000;
SELECT CO.NAME, COUNT(*) AS NumberOfLanguages FROM COUNTRYLANGUAGE CL
JOIN COUNTRY CO ON CL.COUNTRYCODE = CO.CODE
GROUP BY CO.NAME;
SELECT CO.NAME, COUNT(*) AS NumberOfCities from CITY CI
JOIN COUNTRY CO ON CI.COUNTRYCODE = CO.CODE
WHERE CI.POPULATION > 1000000
GROUP BY CO.NAME;
SELECT * FROM COUNTRY;
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT * FROM COUNTRYLANGUAGE WHERE COUNTRYCODE = 'DEU';
SELECT * FROM COUNTRY WHERE NAME = 'POLAND';
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL' AND POPULATION > 1000000;
SELECT * FROM countrylanguage WHERE EXISTS (
    SELECT * FROM country WHERE countrylanguage.CountryCode = country.Code AND country.Population < 10000000);
SELECT DISTINCT CONTINENT FROM COUNTRY
WHERE CONTINENT NOT IN (
SELECT CONTINENT FROM COUNTRY WHERE NAME = 'UNITED STATES');
SELECT * FROM CITY WHERE NAME LIKE 'A%';
SELECT * FROM COUNTRY WHERE NAME LIKE 'P%' OR NAME LIKE 'S%';
SELECT * FROM CITY WHERE NAME LIKE '%BURG';
SELECT * FROM COUNTRY WHERE NAME LIKE '%A%' OR NAME LIKE '%E%';
SELECT * FROM CITY WHERE NAME LIKE 'NEW%' OR NAME LIKE 'LOS%';
SELECT * FROM COUNTRYLANGUAGE WHERE LANGUAGE LIKE '%ESE' OR LANGUAGE LIKE '%IAN';
SELECT * FROM COUNTRY ORDER BY NAME;
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL' ORDER BY POPULATION DESC;
SELECT * FROM COUNTRY ORDER BY SURFACEAREA DESC;
SELECT * FROM CITY WHERE COUNTRYCODE = 'RUS' ORDER BY NAME DESC;
SELECT * FROM COUNTRY ORDER BY NAME LIMIT 10;