SELECT NAME FROM COUNTRY;
SELECT NAME, SURFACEAREA FROM COUNTRY;
SELECT NAME FROM COUNTRY WHERE CONTINENT = 'EUROPE';
SELECT NAME FROM COUNTRY WHERE POPULATION > 10000000;
SELECT NAME, POPULATION FROM COUNTRY WHERE POPULATION > 10000000 AND CONTINENT = 'EUROPE';
SELECT NAME FROM COUNTRY ORDER BY NAME;
SELECT NAME, CAPITAL, POPULATION FROM COUNTRY WHERE NAME = 'POLAND';
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT CO.NAME, CI.NAME AS CAPITAL 
FROM COUNTRY CO
JOIN CITY CI ON CO.CAPITAL = CI.ID
WHERE CI.POPULATION > 500000;
SELECT CO.NAME, COUNT(*) AS NumberOfLanguages FROM COUNTRYLANGUAGE CL
JOIN COUNTRY CO ON CL.COUNTRYCODE = CO.CODE
GROUP BY CO.NAME;
SELECT CO.NAME, COUNT(*) AS NumberOfCities from CITY CI
JOIN COUNTRY CO ON CI.COUNTRYCODE = CO.CODE
WHERE CI.POPULATION > 1000000
GROUP BY CO.NAME;
SELECT * FROM COUNTRY;
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT * FROM COUNTRYLANGUAGE WHERE COUNTRYCODE = 'DEU';
SELECT * FROM COUNTRY WHERE NAME = 'POLAND';
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL' AND POPULATION > 1000000;
SELECT * FROM countrylanguage WHERE EXISTS (
    SELECT * FROM country WHERE countrylanguage.CountryCode = country.Code AND country.Population < 10000000);
SELECT DISTINCT CONTINENT FROM COUNTRY
WHERE CONTINENT NOT IN (
SELECT CONTINENT FROM COUNTRY WHERE NAME = 'UNITED STATES');
SELECT * FROM CITY WHERE NAME LIKE 'A%';
SELECT * FROM COUNTRY WHERE NAME LIKE 'P%' OR NAME LIKE 'S%';
SELECT * FROM CITY WHERE NAME LIKE '%BURG';
SELECT * FROM COUNTRY WHERE NAME LIKE '%A%' OR NAME LIKE '%E%';
SELECT * FROM CITY WHERE NAME LIKE 'NEW%' OR NAME LIKE 'LOS%';
SELECT * FROM COUNTRYLANGUAGE WHERE LANGUAGE LIKE '%ESE' OR LANGUAGE LIKE '%IAN';
SELECT * FROM COUNTRY ORDER BY NAME;
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL' ORDER BY POPULATION DESC;
SELECT * FROM COUNTRY ORDER BY SURFACEAREA DESC;
SELECT * FROM CITY WHERE COUNTRYCODE = 'RUS' ORDER BY NAME DESC;
SELECT * FROM COUNTRY ORDER BY NAME LIMIT 10;
SELECT * FROM CITY WHERE COUNTRYCODE = 'POL' ORDER BY POPULATION DESC LIMIT 5;
SELECT * FROM COUNTRY ORDER BY SURFACEAREA DESC LIMIT 20;
SELECT * FROM COUNTRY ORDER BY POPULATION LIMIT 5;
SELECT * FROM CITY ORDER BY POPULATION DESC LIMIT 10;
SELECT COUNT(*) AS Total_Countries FROM COUNTRY;
SELECT COUNT(*) AS POLAND FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT SUM(POPULATION) AS Total_Population FROM COUNTRY;
SELECT SUM(POPULATION) AS Total_Population_Poland FROM CITY WHERE COUNTRYCODE = 'POL';
SELECT SUM(SURFACEAREA) AS Total_SurfaceArea_NA FROM COUNTRY WHERE CONTINENT = 'NORTH AMERICA';
SELECT SUM(LIFEEXPECTANCY) AS Total_Life_Exp FROM COUNTRY;
SELECT CONTINENT, SUM(POPULATION) AS Total_Population FROM COUNTRY GROUP BY CONTINENT;
SELECT CONTINENT, COUNT(*) AS Number_Of_Countries FROM COUNTRY GROUP BY CONTINENT;
SELECT CONTINENT, AVG(LIFEEXPECTANCY) AS Avg_Life_Exp FROM COUNTRY GROUP BY CONTINENT;
SELECT CONTINENT, ROUND(AVG(LIFEEXPECTANCY),2) AS Avg_Life_Exp FROM COUNTRY GROUP BY CONTINENT;
SELECT CONTINENT, MIN(SURFACEAREA) AS Min_Area FROM COUNTRY GROUP BY CONTINENT;
SELECT COUNTRYCODE, COUNT(*) AS Num_Cities FROM CITY GROUP BY COUNTRYCODE;
SELECT CONTINENT,  COUNT(*) As City FROM COUNTRY WHERE POPULATION > 50000000 GROUP BY CONTINENT;
SELECT CONTINENT, COUNT(*) AS Number_Of_Countries FROM COUNTRY GROUP BY CONTINENT HAVING COUNT(*) >= 5;
SELECT NAME, LIFEEXPECTANCY FROM COUNTRY HAVING LIFEEXPECTANCY >= 80;
SELECT LANGUAGE, COUNT(*) AS Number_Of_Cont FROM COUNTRYLANGUAGE GROUP BY LANGUAGE HAVING COUNT(*) >= 3;
SELECT CONTINENT, SUM(SURFACEAREA) AS Total_SurfaceArea FROM COUNTRY GROUP BY CONTINENT HAVING SUM(SURFACEAREA) > 10000000;
SELECT NAME, POPULATION, SURFACEAREA FROM COUNTRY HAVING POPULATION < 10000000 AND SURFACEAREA > 500000;
SELECT CONCAT(NAME,' - ', CAPITAL) AS COUNTRY_CAPITAL FROM COUNTRY;
SELECT SUBSTRING(NAME, 1, 3) AS First_Three_Char FROM COUNTRY;
SELECT NAME, SUBSTRING(NAME, 1, 5) AS Short_Name FROM CITY WHERE LENGTH(NAME) > 5;
SELECT SUBSTRING(CONTINENT, 1, LENGTH(CONTINENT) - 1) AS SHORT_CONTINENT FROM COUNTRY;
SELECT NAME, SUBSTRING(NAME, LENGTH(NAME) - 1, 2) AS Last_Two_Letters FROM CITY;
SELECT SUBSTRING(LANGUAGE, 1, 3) AS SHORT_LANGUAGE FROM COUNTRYLANGUAGE;
SELECT NAME, SUBSTRING(NAME, - 2, 2) AS SHORT_NAME FROM COUNTRY;
SELECT TRIM(NAME) AS TRIM_NAME FROM COUNTRY;
SELECT CURDATE() AS AKTUALNA_DATA;
SELECT CURTIME() AS AKTUALNA_GODZINA;
SELECT * FROM CITY WHERE COUNTRYCODE = (SELECT CODE FROM COUNTRY WHERE NAME = 'POLAND');
SELECT DISTINCT CONTINENT FROM COUNTRY WHERE POPULATION > ( SELECT AVG(POPULATION) FROM COUNTRY);
SELECT * FROM Country WHERE Capital IN (SELECT ID FROM City WHERE CountryCode IN (SELECT Code FROM Country WHERE Continent = 'Europe'));
